# Generated by Django 5.1.4 on 2025-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(blank=True, default='', max_length=200)),
                ('dob', models.CharField(blank=True, default='', max_length=200)),
                ('referral_code', models.CharField(blank=True, default='', max_length=50)),
                ('referrer_by', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('profile_image', models.CharField(blank=True, default='', max_length=300)),
                ('role', models.CharField(default='', max_length=100)),
                ('special_offers', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
