# Generated by Django 5.1.4 on 2025-03-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('custom_url', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
