# Generated by Django 5.1.4 on 2025-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklab_app', '0002_shortenedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
