# Generated by Django 5.1.4 on 2025-03-26 00:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklab_app', '0003_alter_shortenedurl_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(default='Unknown', max_length=255)),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(default='Unknown', max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('browser', models.CharField(default='Unknown', max_length=50)),
                ('os', models.CharField(default='Unknown', max_length=50)),
                ('is_mobile', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='linklab_app.shortenedurl')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['short_url', 'timestamp'], name='linklab_app_short_u_0e7e37_idx'), models.Index(fields=['ip_address'], name='linklab_app_ip_addr_15ea72_idx')],
            },
        ),
    ]
